# Generated by Django 5.2.14 on 2026-05-25 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efrontend', '0002_alter_airecommendation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='airecommendation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='score',
        ),
    ]
