# Generated by Django 5.2.14 on 2026-05-24 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing & Fashion', 'Clothing & Fashion'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Grocery & Daily Essentials', 'Grocery & Daily Essentials'), ('Glass & Lens (Optical/Eyewear)', 'Glass & Lens (Optical/Eyewear)'), ('Cafe (Coffee Shop / F&B E-commerce)', 'Cafe (Coffee Shop / F&B E-commerce)'), ('Hotels (Hospitality / Booking Platform)', 'Hotels (Hospitality / Booking Platform)'), ('Liquor Shop (Alcoholic Beverages)', 'Liquor Shop (Alcoholic Beverages)')], default='Electronics', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_registration', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('theme_color', models.CharField(default='#6366f1', max_length=20)),
                ('theme_color_secondary', models.CharField(default='#4f46e5', max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=200)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_password', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='company.company')),
            ],
        ),
    ]
