# Generated by Django 5.2.11 on 2026-06-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_type',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Electronics & Technology', 'Electronics & Technology'), ('Clothing & Fashion', 'Clothing & Fashion'), ('Cosmetics & Beauty', 'Cosmetics & Beauty'), ('Home, Furniture & Garden', 'Home, Furniture & Garden'), ('Grocery & Food', 'Grocery & Food'), ('Cafes & Coffee Shops', 'Cafes & Coffee Shops'), ('Hotels & Lodging', 'Hotels & Lodging'), ('Pet Supplies', 'Pet Supplies'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Automotive & Motorcycle', 'Automotive & Motorcycle'), ('Health & Wellness', 'Health & Wellness'), ('Baby & Maternity', 'Baby & Maternity'), ('Office & School Supplies', 'Office & School Supplies'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Books, Music & Media', 'Books, Music & Media'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Luggage & Travel Accessories', 'Luggage & Travel Accessories'), ('Pharmacy & Medical Supplies', 'Pharmacy & Medical Supplies')], db_column='business_type', default='Electronics & Technology', max_length=100, verbose_name='Business Type'),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Algoflow-E', max_length=200)),
                ('email', models.EmailField(default='contact@algoflow-e.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opening_hours_weekday', models.CharField(default='Sun - Fri: 10AM - 7:30PM', max_length=100)),
                ('opening_hours_weekend', models.CharField(default='Saturday: 11AM - 6PM', max_length=100)),
                ('show_store_locations', models.BooleanField(default=True)),
                ('show_information', models.BooleanField(default=True)),
                ('show_policies', models.BooleanField(default=True)),
                ('show_customer_service', models.BooleanField(default=True)),
                ('location_title', models.CharField(default='Our Store Locations', max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer_settings', to='company.company')),
            ],
        ),
    ]
