# Generated by Django 5.2.11 on 2026-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0002_remove_company_business_type_company_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['company', 'role'], name='account_myu_company_01991b_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['company', 'created_at'], name='account_myu_company_5815c1_idx'),
        ),
    ]
