# Generated by Django 5.2.14 on 2026-05-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('eadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='company.company'),
        ),
    ]
