# Generated by Django 5.2.14 on 2026-05-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('eadmin', '0002_possale_company'),
        ('efrontend', '0002_alter_airecommendation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryfeature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='company.company'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfeature',
            unique_together={('company', 'category', 'feature_name')},
        ),
    ]
